### ISSUE TITLE
I need another text box below my website header box

### ISSUE THREAD

**Issue by JazyJayz** [JazyJayz/YoungProgrammersWebsite#1]
i have some texts for put inside the website.I need another text box inside the website(I don't have enough time for it but i can help you). I'll write the texts later i just need the empty box.
i have this things for showing in website:
2 images
2 titles below images
2 text box below titles
2 button below text boxes
I would appreciate it if anybody help me.feel free to ask any questions

**Comment by Gaurav-Punjabi** [comment]
Can I work on this issue?

**Comment by erfansaberi** [comment]
Hi, May I work on this?

**Comment by JazyJayz** [comment]
Feel free to work and asking questions
